//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t check(int64_t * str);

// --------------------- Global Variables ---------------------

struct _IO_FILE * g1 = NULL; // 0x404030

// ------------------------ Functions -------------------------

// Address range: 0x401156 - 0x4012a5
int64_t check(int64_t * str) {
    int64_t result = 1; // 0x401173
    if (strlen((char *)str) != 27) {
      lab_0x40129f_2:
        // 0x40129f
        return result;
    }
    int32_t v1 = 0;
    int32_t v2 = 0;
    for (int64_t i = 0; i < 23; i++) {
        // 0x401280
        int64_t v3; // bp-8, 0x401156
        char * v4 = (char *)((int64_t)&v3 - 80 + i); // 0x401211
        int32_t v5 = 0; // 0x40127c
        int32_t v6 = v1;
        int32_t v7 = v6 + (int32_t)(v6 == 0);
        int32_t v8 = 1 << (7 - v5) % 32 & (int32_t)*v4; // 0x401219
        char v9 = *(char *)((int64_t)v2 + (int64_t)str); // 0x40122e
        int32_t v10 = 1 << (7 - v7) % 32 & (int32_t)v9; // 0x401234
        result = 1;
        if (v10 >= 0 == (v10 != 0) != (v8 >= 0 == (v8 != 0))) {
            return result;
        }
        // 0x401249
        v2 += (int32_t)(v7 == 7);
        result = 0;
        if (v2 == strlen((char *)str)) {
            return result;
        }
        // 0x40127c
        v1 = v7 != 7 ? v7 + 1 : 0;
        v5++;
        int32_t v11 = v2; // 0x401284
        while (v5 < 8) {
            // 0x4011d6
            v6 = v1;
            v7 = v6 + (int32_t)(v6 == 0);
            v8 = 1 << (7 - v5) % 32 & (int32_t)*v4;
            v9 = *(char *)((int64_t)v11 + (int64_t)str);
            v10 = 1 << (7 - v7) % 32 & (int32_t)v9;
            result = 1;
            if (v10 >= 0 == (v10 != 0) != (v8 >= 0 == (v8 != 0))) {
                return result;
            }
            // 0x401249
            v2 = v11 + (int32_t)(v7 == 7);
            result = 0;
            if (v2 == strlen((char *)str)) {
                return result;
            }
            // 0x40127c
            v1 = v7 != 7 ? v7 + 1 : 0;
            v5++;
            v11 = v2;
        }
    }
    // 0x40129f
    return 0;
}

// Address range: 0x4012a5 - 0x40144a
int main(int argc, char ** argv) {
    int64_t str = 0; // bp-280, 0x4012b0
    printf("Enter the password: ");
    fgets((char *)&str, 256, g1);
    int64_t result; // 0x4012a5
    if ((int32_t)check(&str) != 1) {
        // 0x401439
        puts("Correct!! :D");
        result = 0;
    } else {
        // 0x401428
        puts("Wrong :(");
        result = 1;
    }
    // 0x401448
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (14.2.1)
// Detected functions: 2

